apiVersion: v1
kind: Service
metadata:
  name: apsas-backend
  namespace: __NAMESPACE__
  labels:
    app: apsas-backend
spec:
  type: ClusterIP
  selector:
    app: apsas-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
