apiVersion: v1
kind: Service
metadata:
  name: apsas-backend
  namespace: __NAMESPACE__
  labels:
    app: apsas-backend
  annotations:
    cloud.google.com/backend-config: '{"ports":{"80":"apsas-backend-becfg"}}'
spec:
  type: ClusterIP
  selector:
    app: apsas-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
