server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Dòng này là "phép thuật" cho React Router:
        # Nếu không tìm thấy file thật, hãy đẩy người dùng về index.html để React tự xử lý
        try_files $uri $uri/ /index.html;
    }

    # Cấu hình cache cho các file tĩnh (ảnh, css, js) để web load nhanh hơn
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}