server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  error:
    include-message: never

spring:
  application:
    name: CodeVerse
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  ai:
    model:
      chat: openai
    openai:
      api-key: ${GEMINI_API_KEY} # dùng Gemini API key
      chat:
        base-url: https://generativelanguage.googleapis.com
        api-key: ${GEMINI_API_KEY} # hoặc spring.ai.openai.chat.api-key (tùy version)
        options:
          model: gemini-2.5-flash
        completions-path: /v1beta/openai/chat/completions
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 1000
      thread-name-prefix: app-async-
  datasource:
    url: ${MYSQL}
    username: ${USER}
    password: ${PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GGCLIENTID}
            client-secret: ${GGCLIENT_SECRET}
            scope: email, profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  frontend:
    url: ${URLFONTEND}
  #    https://apsas-fe.vercel.app
  kafka:
    bootstrap-servers: ${KAFKA}
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.use.type.headers: true
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.project.apsas.*"
      group-id: group_one
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.use.type.headers: true
    listener:
      ack-mode: manual_immediate
      concurrency: 3
logging:
  level:
    root: INFO
    com.project.apsas: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
#    org.springframework.kafka.config: DEBUG
#    org.springframework.kafka.listener: DEBUG

message-queue:
  topic:
    mail:
      name: topic-mail
      dlt: topic-mail.DLT
      drop: topic-mail.DLT.DROP
    feedback:
      name: topic-ai
    execute:
      name: topic-execute

cloudinary:
  cloud-name: ddcyjcpx0
  api-key: ${API_KEY_CLOUDINARY}
  api-secret: ${API_SECRET_CLOUDINARY}
  option:
    folder-name: uploads/general
    resource-type: auto

jwt:
  verify:
    ttl-minutes: 10
  refresh:
    ttl-minutes: 120
  signerKey: ${JWTKEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

brevo:
  base-url: https://api.brevo.com/v3
  api-key: ${API_KEY_BREVO}
  template-id: 3
  sender:
    mail: nguyentrongduc447@gmail.com
    name: CodeVerse
jubge:
  base-url: https://ce.judge0.com

mvc:
  throw-exception-if-no-handler-found: true

web:
  resources:
    add-mappings: false

app:
  name: CodeVerse
  kafka:
    topic:
      verify-email: verify-email
